// agentguard opencode-init — set up opencode.ai agent integration
// Writes an AgentGuard plugin to .opencode/plugins/agentguard.ts (repo-level)
// or ~/.opencode/plugins/agentguard.ts (global).
// The plugin calls agentguard opencode-hook via subprocess for before/after hooks.

import { readFileSync, writeFileSync, existsSync, mkdirSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { RESET, BOLD, DIM, FG } from '../colors.js';
import { resolveMainRepoRoot } from '@red-codes/core';
import type { EnforcementMode } from '@red-codes/core';

const HOOK_MARKER = 'opencode-hook';
const LOCAL_BIN = 'node apps/cli/dist/bin.js';

/** Detect if we're in the agentguard development repo (local dev) vs. globally installed. */
function resolveCliPrefix(isGlobal: boolean): { cli: string; isLocal: boolean } {
  const mainRoot = resolveMainRepoRoot();
  const localMarker = join(mainRoot, 'apps', 'cli', 'src', 'bin.ts');
  if (existsSync(localMarker)) {
    return { cli: LOCAL_BIN, isLocal: true };
  }
  if (!isGlobal) {
    const nmBin = join(mainRoot, 'node_modules', '.bin', 'agentguard');
    if (existsSync(nmBin)) {
      return { cli: './node_modules/.bin/agentguard', isLocal: false };
    }
    const nmBinAguard = join(mainRoot, 'node_modules', '.bin', 'aguard');
    if (existsSync(nmBinAguard)) {
      return { cli: './node_modules/.bin/aguard', isLocal: false };
    }
  }
  return { cli: 'agentguard', isLocal: false };
}

/**
 * Generate the TypeScript plugin file content for OpenCode.
 * OpenCode plugins are TypeScript files that export a default plugin object.
 * Each plugin declares `before` and/or `after` hooks.
 */
function generatePluginContent(cli: string, storeSuffix: string, dbPathSuffix: string): string {
  return `// AgentGuard governance plugin for opencode.ai
// Auto-generated by: agentguard opencode-init
// This plugin routes all tool calls through AgentGuard for policy enforcement.
// Docs: https://github.com/AgentGuardHQ/agent-guard

import { execSync } from "node:child_process";

export default {
  name: "agentguard",
  before: (tool: string, input: Record<string, unknown>) => {
    try {
      const payload = JSON.stringify({ tool, input });
      const result = execSync(
        "${cli} ${HOOK_MARKER} before${storeSuffix}${dbPathSuffix}",
        { input: payload, timeout: 30000, encoding: "utf8" }
      ).trim();
      if (result) {
        const parsed = JSON.parse(result) as { decision?: string; reason?: string };
        if (parsed.decision === "deny") {
          throw new Error(\`AgentGuard blocked: \${parsed.reason ?? "policy violation"}\`);
        }
      }
    } catch (err) {
      if (err instanceof Error && err.message.startsWith("AgentGuard blocked:")) {
        throw err;
      }
      // Governance check failed — fail open to avoid blocking the agent
    }
  },
  after: (tool: string, input: Record<string, unknown>, output: unknown) => {
    try {
      const payload = JSON.stringify({ tool, input, output });
      execSync(
        "${cli} ${HOOK_MARKER} after${storeSuffix}${dbPathSuffix}",
        { input: payload, timeout: 10000, encoding: "utf8", stdio: ["pipe", "ignore", "pipe"] }
      );
    } catch {
      // Non-fatal
    }
  },
};
`;
}

const POLICY_CANDIDATES = [
  'agentguard.yaml',
  'agentguard.yml',
  'agentguard.json',
  '.agentguard.yaml',
  '.agentguard.yml',
];

const STARTER_POLICY_TEMPLATE = (mode: EnforcementMode) => `# AgentGuard policy — safety rules for AI coding agents.
# Customize this file to match your project's security requirements.
# Docs: https://github.com/AgentGuardHQ/agent-guard

id: default-policy
name: Default Safety Policy
description: Baseline safety rules for AI coding agents
severity: 4

# Enforcement mode: guide | educate | monitor | enforce
#   guide   — block dangerous actions with corrective suggestions (recommended)
#   educate — allow actions but teach correct patterns
#   monitor — log threats, don't block
#   enforce — block dangerous actions, no suggestions
mode: ${mode}

rules:
  # Protected branches — prevent direct push to main/master
  - action: git.push
    effect: deny
    branches: [main, master]
    reason: Direct push to protected branch
    suggestion: Push to a feature branch and open a pull request instead
    correctedCommand: "git push origin HEAD:feat/my-branch"

  # No force push — prevent history rewriting
  - action: git.force-push
    effect: deny
    reason: Force push rewrites shared history

  # Secrets protection — block writes to sensitive files
  - action: file.write
    effect: deny
    target: .env
    reason: Secrets files must not be modified

  - action: file.write
    effect: deny
    target: ".npmrc"
    reason: npm credentials file must not be modified by agents

  - action: file.write
    effect: deny
    target: "id_rsa"
    reason: SSH private keys must not be modified

  - action: file.write
    effect: deny
    target: "id_ed25519"
    reason: SSH private keys must not be modified

  # Destructive command protection
  - action: shell.exec
    effect: deny
    target: rm -rf
    reason: Destructive shell commands blocked

  # Deployment protection
  - action: deploy.trigger
    effect: deny
    reason: Deploy actions require explicit authorization

  - action: infra.destroy
    effect: deny
    reason: Infrastructure destruction requires explicit authorization

  # Defaults
  - action: file.read
    effect: allow
    reason: Reading is always safe

  - action: file.write
    effect: allow
    reason: File writes allowed by default
`;

function generateStarterPolicy(mode: EnforcementMode = 'guide'): boolean {
  const repoRoot = resolveMainRepoRoot();
  for (const candidate of POLICY_CANDIDATES) {
    if (existsSync(join(repoRoot, candidate))) {
      return false;
    }
  }
  const policyPath = join(repoRoot, 'agentguard.yaml');
  writeFileSync(policyPath, STARTER_POLICY_TEMPLATE(mode), 'utf8');
  process.stderr.write(
    `  ${FG.green}\u2713${RESET}  Policy created: ${FG.cyan}agentguard.yaml${RESET} (${mode} mode)\n`
  );
  return true;
}

function showProtectionSummary(policyGenerated: boolean, mode: EnforcementMode = 'guide'): void {
  process.stderr.write('\n');
  process.stderr.write(`  ${FG.green}${BOLD}AgentGuard is active for OpenCode.${RESET}\n\n`);

  if (mode === 'guide') {
    process.stderr.write(
      `  ${BOLD}Mode: ${FG.cyan}guide${RESET}${BOLD} — dangerous actions blocked with corrective suggestions${RESET}\n\n`
    );
  } else if (mode === 'educate') {
    process.stderr.write(
      `  ${BOLD}Mode: ${FG.blue}educate${RESET}${BOLD} — actions allowed with corrective teaching${RESET}\n\n`
    );
  } else if (mode === 'monitor') {
    process.stderr.write(
      `  ${BOLD}Mode: ${FG.yellow}monitor${RESET}${BOLD} — threats are logged, not blocked${RESET}\n\n`
    );
  } else {
    process.stderr.write(
      `  ${BOLD}Mode: ${FG.red}enforce${RESET}${BOLD} — dangerous actions are blocked${RESET}\n\n`
    );
  }

  process.stderr.write(`  ${FG.blue}\u25A0${RESET} ${DIM}Track${RESET} all actions with audit trail\n`);
  process.stderr.write('\n');

  process.stderr.write(`  ${BOLD}Next steps:${RESET}\n`);
  if (policyGenerated) {
    process.stderr.write(
      `  ${DIM}1. Edit ${FG.cyan}agentguard.yaml${RESET}${DIM} to customize rules for your project${RESET}\n`
    );
    process.stderr.write(
      `  ${DIM}2. Start an OpenCode session — governance is automatic${RESET}\n`
    );
    process.stderr.write(
      `  ${DIM}3. Run ${FG.cyan}agentguard inspect --last${RESET}${DIM} to review decisions${RESET}\n`
    );
  } else {
    process.stderr.write(
      `  ${DIM}1. Start an OpenCode session — governance is automatic${RESET}\n`
    );
    process.stderr.write(
      `  ${DIM}2. Run ${FG.cyan}agentguard inspect --last${RESET}${DIM} to review decisions${RESET}\n`
    );
  }
  process.stderr.write(`\n  ${DIM}Remove: ${FG.cyan}agentguard opencode-init --remove${RESET}\n\n`);
}

export async function openCodeInit(args: string[] = []): Promise<void> {
  const isGlobal = args.includes('--global') || args.includes('-g');
  const isRemove = args.includes('--remove') || args.includes('--uninstall');

  const storeIdx = args.findIndex((a) => a === '--store');
  const storeBackend = storeIdx !== -1 ? args[storeIdx + 1] : undefined;
  const storeSuffix = storeBackend ? ` --store ${storeBackend}` : '';

  const dbPathIdx = args.findIndex((a) => a === '--db-path');
  const dbPathValue = dbPathIdx !== -1 ? args[dbPathIdx + 1] : undefined;
  const dbPathSuffix = dbPathValue ? ` --db-path "${dbPathValue}"` : '';

  const modeArgIdx = args.findIndex((a) => a === '--mode');
  const modeArg = modeArgIdx !== -1 ? args[modeArgIdx + 1] : undefined;
  const VALID_MODES: EnforcementMode[] = ['guide', 'educate', 'monitor', 'enforce'];
  const selectedMode: EnforcementMode =
    modeArg && VALID_MODES.includes(modeArg as EnforcementMode)
      ? (modeArg as EnforcementMode)
      : 'guide';

  // OpenCode plugins location:
  // Repo-level: .opencode/plugins/agentguard.ts
  // Global: ~/.opencode/plugins/agentguard.ts
  const pluginsDir = isGlobal
    ? join(homedir(), '.opencode', 'plugins')
    : join(process.cwd(), '.opencode', 'plugins');
  const pluginPath = join(pluginsDir, 'agentguard.ts');
  const pluginLabel = isGlobal
    ? '~/.opencode/plugins/agentguard.ts'
    : '.opencode/plugins/agentguard.ts';

  process.stderr.write('\n');
  process.stderr.write(`  ${BOLD}AgentGuard OpenCode Integration${RESET}\n\n`);

  if (isRemove) {
    removePlugin(pluginPath, pluginLabel);
    return;
  }

  if (!existsSync(pluginsDir)) {
    mkdirSync(pluginsDir, { recursive: true });
  }

  if (existsSync(pluginPath)) {
    try {
      const content = readFileSync(pluginPath, 'utf8');
      if (content.includes(HOOK_MARKER)) {
        process.stderr.write(
          `  ${FG.yellow}Already configured.${RESET} AgentGuard plugin found in ${pluginLabel}.\n`
        );
        process.stderr.write(`  ${DIM}Use --remove to uninstall.${RESET}\n\n`);
        return;
      }
    } catch {
      // Unreadable — overwrite
    }
  }

  const { cli } = resolveCliPrefix(isGlobal);
  const pluginContent = generatePluginContent(cli, storeSuffix, dbPathSuffix);
  writeFileSync(pluginPath, pluginContent, 'utf8');

  process.stderr.write(
    `  ${FG.green}\u2713${RESET}  Plugin installed: ${FG.cyan}${pluginLabel}${RESET}\n`
  );
  process.stderr.write(`  ${DIM}before: governance enforcement (all tools)${RESET}\n`);
  process.stderr.write(`  ${DIM}after:  error monitoring (shell)${RESET}\n`);
  if (storeBackend) {
    process.stderr.write(`  ${DIM}Storage: ${storeBackend}${RESET}\n`);
  }
  process.stderr.write('\n');

  // Ensure telemetry directories exist
  const repoRoot = resolveMainRepoRoot();
  const dirs = ['.agentguard/events', '.agentguard/decisions'];
  for (const dir of dirs) {
    const dirPath = join(repoRoot, dir);
    if (!existsSync(dirPath)) {
      mkdirSync(dirPath, { recursive: true });
    }
  }

  const policyGenerated = generateStarterPolicy(selectedMode);
  showProtectionSummary(policyGenerated, selectedMode);
}

function removePlugin(pluginPath: string, pluginLabel: string): void {
  if (!existsSync(pluginPath)) {
    process.stderr.write(
      `  ${DIM}No plugin file found at ${pluginLabel}. Nothing to remove.${RESET}\n\n`
    );
    return;
  }

  try {
    const content = readFileSync(pluginPath, 'utf8');
    if (!content.includes(HOOK_MARKER)) {
      process.stderr.write(
        `  ${DIM}No AgentGuard hook found in ${pluginLabel}. Nothing to remove.${RESET}\n\n`
      );
      return;
    }
  } catch {
    process.stderr.write(
      `  ${FG.red}Error:${RESET} Could not read ${pluginLabel}.\n\n`
    );
    return;
  }

  // Remove the file entirely (it was generated by agentguard opencode-init)
  try {
    unlinkSync(pluginPath);
    process.stderr.write(
      `  ${FG.green}\u2713${RESET}  Plugin removed: ${FG.cyan}${pluginLabel}${RESET}\n`
    );
    process.stderr.write(
      `  ${DIM}AgentGuard governance will no longer monitor in OpenCode.${RESET}\n\n`
    );
  } catch {
    process.stderr.write(`  ${FG.red}Error:${RESET} Could not remove ${pluginLabel}.\n\n`);
  }
}
